spring:
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    password:
codedream:
  redis:
    lock:
      enabled: true
      address: redis://127.0.0.1:6379
      datebase: 0
      pool-size: 20
      idle-size: 5
      idle-timeout: 60000
      connection-timeout: 60000
      timeout: 10000
      mode: single
    rate-limiter:
      enabled:true
